name: build Velero containers on Dockerfile change

on:
  pull_request:
    branches:
      - 'main'
      - 'release-**'
    paths:
      - 'Dockerfile'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    # Use the JSON key in secret to login gcr.io
    - uses: 'docker/login-action@v1'
      with:
        registry: 'gcr.io' # or REGION.docker.pkg.dev
        username: '_json_key'
        password: '${{ secrets.GCR_SA_KEY }}'

    # Push image to GCR to facilitate some environments that have rate limitation to docker hub, e.g. vSphere.
    - name: Publish container image to GCR
      #if: github.repository == 'vmware-tanzu/velero'
      if: github.repository == 'blackpiglet/velero-test'
      run: |
        REGISTRY=gcr.io/velero-gcp ./hack/docker-push.sh